FFFF.FF........F.FF
======================================================================
FAIL: test_eval_1 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 62, in test_eval_1
    self.assertEqual(v, 20)
AssertionError: 1 != 20

======================================================================
FAIL: test_eval_2 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 66, in test_eval_2
    self.assertEqual(v, 125)
AssertionError: 1 != 125

======================================================================
FAIL: test_eval_3 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 70, in test_eval_3
    self.assertEqual(v, 89)
AssertionError: 1 != 89

======================================================================
FAIL: test_eval_4 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 74, in test_eval_4
    self.assertEqual(v, 174)
AssertionError: 1 != 174

======================================================================
FAIL: test_eval_6 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 82, in test_eval_6
    self.assertEqual(v, 2)
AssertionError: 1 != 2

======================================================================
FAIL: test_eval_7 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 86, in test_eval_7
    self.assertEqual(v, 89)
AssertionError: 1 != 89

======================================================================
FAIL: test_solve (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 120, in test_solve
    self.assertEqual(w.getvalue(), "1 10 20\n100 200 125\n201 210 89\n900 1000 174\n")
AssertionError: '1 10 1\n100 200 1\n201 210 1\n900 1000 1\n' != '1 10 20\n100 200 125\n201 210 89\n900 1000 174\n'
- 1 10 1
?      ^
+ 1 10 20
?      ^^
- 100 200 1
+ 100 200 125
?          ++
- 201 210 1
?         ^
+ 201 210 89
?         ^^
- 900 1000 1
+ 900 1000 174
?           ++


======================================================================
FAIL: test_solve3 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 132, in test_solve3
    self.assertEqual(w.getvalue(), "1 2 2\n")
AssertionError: '1 2 1\n' != '1 2 2\n'
- 1 2 1
?     ^
+ 1 2 2
?     ^


======================================================================
FAIL: test_solve4 (__main__.TestCollatz)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestCollatz.py", line 138, in test_solve4
    self.assertEqual(w.getvalue(), "10 1 20\n200 100 125\n210 201 89\n1000 900 174\n")
AssertionError: '10 1 1\n200 100 1\n210 201 1\n1000 900 1\n' != '10 1 20\n200 100 125\n210 201 89\n1000 900 174\n'
- 10 1 1
?      ^
+ 10 1 20
?      ^^
- 200 100 1
+ 200 100 125
?          ++
- 210 201 1
?         ^
+ 210 201 89
?         ^^
- 1000 900 1
+ 1000 900 174
?           ++


----------------------------------------------------------------------
Ran 19 tests in 0.004s

FAILED (failures=9)
